server:
  port: 8001
spring:
  redis:
    database: 0
    host: 1.14.167.25
    port: 6379
    password: Yoav19731006
# dev 开发环境开启mybatis日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 设置域名，在java代码中获取，这里是资源配置
website:
  domain-name: localhost
# 定义freemarker生成的html位置
freemarker:
  html:
    target: C:\Users\86467\Desktop\imooc-news-dev\imooc-news-dev-service-article\src\main\resources\freemarker_html
    article: D:\apache-tomcat-9.0.30-windows-x64\apache-tomcat-9.0.30\webapps\imooc-news\portal\a



