############################################################
#
# 网关zuul
# web访问端口号  约定：7070
#
############################################################
server:
  port: 7070
  tomcat:
    uri-encoding: UTF-8

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: springcloud-zuul-server
  redis:
    database: 0
    host: 1.14.167.25
    port: 6379
    password: Yoav19731006

# 路由规则
zuul:
  routes:
    service-article:                # 配置的微服务路由id，微服务实例id
      path: /service-article/**     # 请求路径(前缀)，匹配规则：localhost:6000/article-service/abc
      service-id: service-article   # 微服务实例id
  #      url: http://192.168.1.4:8001   # 转发请求到指定微服务的ip地址
  prefix: /api  # 前缀


eureka:
  server:
    hostname: localhost
    port: 7000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 注册中心的地址，表示我当前微服务要登记户口到指定的派出所
       defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
      # 微服务向eureka集群中注册
#      defaultZone: http://eureka-cluster-7001:7001/eureka/,http://eureka-cluster-7002:7002/eureka/,http://eureka-cluster-7003:7003/eureka/

# ip请求限制的参数配置
blackIp:
  continueCounts: ${counts:10}    # ip连续请求的次数
  timeInterval: ${interval:10}    # ip判断的事件间隔，单位：秒
  limitTimes: ${times:15}         # 限制的事件，单位：秒

